export default defineAppConfig({
  title: 'app.config.ts',
  gameList: {
    "kanto": "Red_Green_Blue_Yellow",
    "johto": "Gold_Silver_Crystal",
    "hoenn": "Ruby_Sapphire_Emerald",
    "sinnoh": "Diamond_Pearl_Platinum",
    "unova_bw": "Black_White",
    "unova_b2w2": "Black2_White2",
    "central_kalos": "X_Y",
    "coast_kalos": "X_Y",
    "mountain_kalos": "X_Y",
    "alola_sm": "Sun_Moon",
    "alola_usum": "UltraSun_UltraMoon",
    "galar": "Sword_Shield",
    "isle_of_armor": "Sword_Shield",
    "crown_tundra": "Sword_Shield",
    "hisui": "LegendsArceus",
    "paldea": "Scarlet_Violet",
    "kitakami": "Scarlet_Violet",
    "blueberry": "Scarlet_Violet",
  },
  verExchange: {
    "red": "赤",
    "green": "緑",
    "blue": "青",
    "pikachu": "ピカチュウ",
    "gold": "金",
    "silver": "銀",
    "crystal": "クリスタル",
    "ruby": "ルビー",
    "sapphire": "サファイア",
    "emerald": "エメラルド",
    "diamond": "ダイアモンド",
    "pearl": "パール",
    "platinum": "プラチナ",
    "black": "ブラック",
    "white": "ホワイト",
    "black2": "ブラック2",
    "white2": "ホワイト2",
    "x": "X",
    "y": "Y",
    "sun": "サン",
    "moon": "ムーン",
    "ultrasun": "ウルトラサン",
    "ultramoon": "ウルトラムーン",
    "sword": "ソード",
    "shield": "シールド",
    "legendsarceus": "Legendsアルセウス",
    "scarlet": "スカーレット",
    "violet": "バイオレット",
  },
  blogs: [
    {
      "no": "1",
      "title": "シート内のチャートを全削除するマクロ",
      "contents": "",
      "tag": []
    },
    {
      "no": "2",
      "title": "test2",
      "contents": "test2",
      "tag": []
    },
  ]
})
